Pushing sync to dev branch. Managed to get wallpaper menu to work but yad designed it to be a menu for applications so this may not work for what I need it to do.
Managed to get settings to work get into the right function but columns are not working properly for creating the list.

diff --git a/releases/wpe2k/debian/opt/wpe2k/wpe2k b/releases/wpe2k/debian/opt/wpe2k/wpe2k
--- a/releases/wpe2k/debian/opt/wpe2k/wpe2k
+++ b/releases/wpe2k/debian/opt/wpe2k/wpe2k
@@ -6,62 +6,81 @@
 # Credits: 
 # Graphical interface: YAD - https://yad-guide.ingk.se/
 
-# Define Common Paths
-wpe2kDir="/opt/wpe2k/"
-configMenu="config/menus.json"
+menuJson=$(cat config/menus.json)
 
-# Globals
-wpe2kRunning="true"
+# Set Globals
+# Outputs a list of variables from the .menus[].global[] array in the menus.json file. Please reference that file to understand what variables are genearted here.
+globalKey=$(echo $menuJson | jq '.menus[0].global[]' | jq -r '.var')
+for globalValue in $(echo $globalKey)
+do
+    # echo $menuJson | jq -r '.menus[0].global[] | select(.var=="'${globalValue}'")'
+    content=$(echo $menuJson | jq -r --arg n $globalValue '.menus[0].global[] | select(.var == $n) | .content' )
+    declare $globalValue=$(echo "--$globalValue="$content"")
+done
+
+name=$(echo $name | cut -d '=' -f 2)
 
 getMenu() {
-    unset menu menuName width height location title type hidden buttons id buttonName button columns column key columnKeys rows menuMain
-    menu=$(cat $configMenu | jq -r '.menus[] | select(.name == "'$1'")')
-    menuName=$(echo ${menu} | jq -r '.name')
+    # unset menu title type buttons id buttonName button columns column key columnKeys rows menuMain
+    menu=$(echo $menuJson | jq -r '.menus[].'$menuName'//empty')
+    echo $menu
     echo "Current Menu: $menuName"
-    width=$(echo $menu | jq -r '.width'); width=$(echo "--width=$width")
+    echo "Global Menu Settings"
     echo $width
-    height=$(echo $menu | jq -r '.height'); height=$(echo "--height=$height")
     echo $height
-    title=$(echo $menu | jq -r '.title'); title=$(echo "--title=$title")
-    echo $title
-    type=$(echo $menu | jq -r '.type')
-    echo $type
-    location=$(echo $menu | jq -r '.location')
     echo $location
-    hidden=$(echo $menu | jq -r '.hidden')
-    echo $hidden
-    #    buttons=$(echo $menu | jq -r '.buttons[] | ([.id]) | @sh')
-    #    for id in $(echo $buttons)
-    #    do
-    #        buttonName=$(echo $menu | jq -r '.buttons['$id'] | ([.name]) | @sh' | tr -d \')
-    #        button=$(echo $button;echo "--button=$buttonName:$id ")
-    #    done
-    #    echo $button
-    columns=$(echo $menu | jq -r '.body[].columns[0] | keys_unsorted[]')
-    for key in $(echo $columns)
+    title=$(echo $menu | jq -r '.title'); title=$(echo "--title=$name - $title")
+    echo $title
+    boarders=$(echo $menu | jq -r '.boarders'); boarders=$(echo "--boarders=$boarders")
+    echo $boarders
+    textalign=$(echo $menu | jq -r '.textalign'); textalign=$(echo "--text-align=$textalign")
+    echo $textalign
+    flags=$(echo $menu | jq -r '.flags')
+    echo $flags
+    buttons=$(echo $menu | jq -r '.buttons[] | ([.id]) | @sh')
+    for id in $(echo $buttons)
     do
-        column=$(echo $column;echo "--column=$key ")
-        columnKeys=$(echo $columnKeys;echo ".$key, ")
+        buttonName=$(echo $menu | jq -r '.buttons['$id'] | ([.name]) | @sh' | tr -d \')
+        button=$(echo $button;echo "--button=$buttonName:$id ")
     done
-    echo $column
-    columnKeys=${columnKeys::-2}
-    rows=$(echo $menu | jq -r '.body[].columns[] | (['"$columnKeys"']) | @sh' | tr -d \')
+    echo $button
+    # This will leverage the field type to filter by one way or another. Some yad types start with type= and some dont' This same json field will be used for either.
+    type=$(echo $menu | jq -r '.type')
+    if [[ "$type" == "" ]]
+    then
+        flags=$(echo "$type $flags")
+    else
+        columns=$(echo $menu | jq -r '.body[].columns[] | keys_unsorted[]')
+        for key in $(echo $columns)
+        do
+            column=$(echo $column;echo "--column=$key ")
+            columnKeys=$(echo $columnKeys;echo ".$key, ")
+        done
+        echo $column
+        columnKeys=${columnKeys::-2}
+        echo $columnKeys
+        rows=$(echo $menu | jq -r '.body[].columns[] | (['"$columnKeys"'])' | tr -d \')
+    fi
 }
 
-mainMenu() {
-    menuName="main"
+wallpaperMenu() {
+    menuName="wallpaper"
     getMenu $menuName
     # main body
-    while menuMain=$(yad $width $height $location $title $hidden $type $button $column $rows)
+    while menuContent=$( \
+            yad $type $width $height $location \
+            "$title" $boarders $textalign \
+            "$flags" \
+            $button  # Menu specific variables. These will pull from the object with the same name as $menuName
+        )
     do
-        echo $menuMain
         if [ $? == 1 ]
         then
             echo "Error thrown"
             exit 1
         else
-            menuId=$(echo $menuMain | cut -d \| -f 1)
-            menuFull=$(echo $menuMain | sed 's/|/ /g')
+            menuId=$(echo $menuContent | cut -d \| -f 1)
+            menuFull=$(echo $menuContent | sed 's/|/ /g')
             case $menuId in
             1) echo "Selected: $menuFull" ;;
             2) echo "Selected: $menuFull" ;;
@@ -77,27 +96,38 @@ mainMenu() {
 }
 
 settingsMenu() {
+    menuName="settings"
+    getMenu $menuName
     # main body
-    title="Komorebi WPE"
-    prompt="Settings"
-    wpList=$(yad \
-        --title="$title" \
-        --text="$prompt" \
-        --list \
-        --column=ICON:IMG \
-        --column="name" \
-        --column="description" \
-        --imagelist \
-        $(cat data/wallpaper.json | jq -r '.wallpapers[] | [.previewImage, .title, .info.VideoFileName] | @sh' | tr -d \')
-    )
-
-    if [[ $? -eq 1 ]]
-    then
-        exit 1
-    else
-        echo "testing"
-    fi
-    mainMenu
+    while menuContent=$( \
+            yad $type $width $height $location \
+            "$type" "$title" $boarders $textalign \
+            "$flags" \
+            $button  # Menu specific variables. These will pull from the object with the same name as $menuName
+        )
+    do
+        if [ $? == 1 ]
+        then
+            echo "Error thrown"
+            exit 1
+        else
+            menuId=$(echo $menuContent | cut -d \| -f 1)
+            menuFull=$(echo $menuContent | sed 's/|/ /g')
+            case $menuId in
+            1) echo "Selected: $menuFull" ;;
+            2) echo "Selected: $menuFull" ;;
+            3) echo "Selected: $menuFull" ;;
+            *) echo "confused..."
+                echo "reloading data..."
+                getMenu "main"
+                ;;
+            esac
+        fi
+        getMenu $menuName
+    done
 }
 
-mainMenu
+case $1 in
+wallpaper) wallpaperMenu ;;
+settings) settingsMenu ;;
+esac
